global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "carematch-api-live"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["carematch-api-726123996575.us-central1.run.app"]

  - job_name: "carematch-prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:9090"]
