"""
Postgres persistence layer (migrated from SQLite; Supabase-ready).

Why Postgres now: SQLite's one-file model can't survive a container that
has no persistent disk (Cloud Run, Spaces) and can't be shared by more
than one process. Postgres moves the data off the box entirely, so the
API becomes stateless and horizontally scalable. Supabase is just managed
Postgres, so the same DATABASE_URL works locally and in production.

Layout is unchanged from the SQLite version -- five tables matching the
API's object model:
  trials -> rules            (1:N)
  assessments -> rule_results (1:N)
  assessments -> decisions    (1:1, nullable; a decision never exists
                               until a coordinator records one)

Two deliberate compatibility decisions, both load-bearing:

1. created_at stays TEXT, not TIMESTAMPTZ. main.py's AssessmentSummary
   declares `created_at: str`, and pydantic v2 raises on a datetime where
   str is declared -- a TIMESTAMPTZ column would pass every schema check
   and then 500 on GET /assessments. The default reproduces SQLite's
   datetime('now') byte-for-byte: UTC, second precision, space separator.
   Because precision is still one second, list_assessments keeps its
   assessment_id tiebreaker for rows written in the same second.

2. Connections come from a pool. SQLite's connect-per-call was free
   (a file open); against a remote Postgres it is a TCP + TLS handshake
   per query, so every store function borrows from a ThreadedConnectionPool
   and returns it. The per-call transaction boundary is identical to
   before: commit on success, rollback on exception, always release.
"""

import os
import threading
from contextlib import contextmanager

import psycopg2
import psycopg2.extras
import psycopg2.pool

# Supabase hands you exactly this string (Project Settings -> Database ->
# Connection string -> URI). Nothing else is read, so local and production
# differ only by the value of this one variable.
DATABASE_URL = os.environ.get("DATABASE_URL")

_POOL = None
_POOL_LOCK = threading.Lock()

SCHEMA = """
CREATE TABLE IF NOT EXISTS trials (
    trial_id   TEXT PRIMARY KEY,
    trial_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS rules (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_id  TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    rule_id   TEXT NOT NULL,
    rule_text TEXT NOT NULL,
    category  TEXT NOT NULL,
    UNIQUE (trial_id, rule_id)
);

CREATE TABLE IF NOT EXISTS assessments (
    assessment_id    TEXT PRIMARY KEY,
    trial_id         TEXT NOT NULL REFERENCES trials(trial_id),
    patient_id       TEXT NOT NULL,
    patient_record   TEXT NOT NULL,
    suggested_status TEXT NOT NULL,
    provider_used    TEXT NOT NULL,
    model_used       TEXT NOT NULL,
    created_at       TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS rule_results (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id TEXT NOT NULL REFERENCES assessments(assessment_id) ON DELETE CASCADE,
    rule_id       TEXT NOT NULL,
    rule_text     TEXT NOT NULL,
    status        TEXT NOT NULL,
    evidence      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS decisions (
    assessment_id   TEXT PRIMARY KEY REFERENCES assessments(assessment_id) ON DELETE CASCADE,
    decision        TEXT NOT NULL,
    decision_reason TEXT,
    decided_at      TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);
"""


def _get_pool():
    """Lazily build the pool so importing db.py never requires a reachable
    database (tests and tooling import this module freely)."""
    global _POOL
    if _POOL is None:
        with _POOL_LOCK:
            if _POOL is None:
                if not DATABASE_URL:
                    raise RuntimeError(
                        "DATABASE_URL is not set. Copy api/.env.example to api/.env "
                        "and set it to your Postgres/Supabase connection URI."
                    )
                _POOL = psycopg2.pool.ThreadedConnectionPool(
                    minconn=1,
                    maxconn=int(os.environ.get("DB_POOL_MAX", "10")),
                    dsn=DATABASE_URL,
                    cursor_factory=psycopg2.extras.RealDictCursor,
                )
    return _POOL


def reset_pool():
    """Drop the pool so the next call reconnects. Used by tests that set
    DATABASE_URL after this module was already imported."""
    global _POOL
    with _POOL_LOCK:
        if _POOL is not None:
            try:
                _POOL.closeall()
            except Exception:
                pass
        _POOL = None


@contextmanager
def _connect():
    """Borrow a pooled connection for one logical operation. Same
    transaction semantics as the SQLite version: commit on success,
    rollback on any exception, always hand the connection back."""
    pool = _get_pool()
    conn = pool.getconn()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        pool.putconn(conn)


def init_db():
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(SCHEMA)


def create_trial(trial_id: str, trial_name: str, rules: list[dict]):
    """Register (or re-register) a trial and its rules. Re-registering the
    same trial_id replaces its rules, so re-running the eval batch or a test
    suite doesn't error on duplicate keys."""
    with _connect() as conn:
        with conn.cursor() as cur:
            # SQLite's INSERT OR REPLACE has no Postgres equivalent; the
            # upsert below is the behaviour that was actually wanted --
            # and unlike INSERT OR REPLACE it does NOT delete-then-insert
            # the trials row, so assessments' FK to it is never disturbed.
            cur.execute(
                "INSERT INTO trials (trial_id, trial_name) VALUES (%s, %s) "
                "ON CONFLICT (trial_id) DO UPDATE SET trial_name = EXCLUDED.trial_name",
                (trial_id, trial_name),
            )
            cur.execute("DELETE FROM rules WHERE trial_id = %s", (trial_id,))
            if rules:
                cur.executemany(
                    "INSERT INTO rules (trial_id, rule_id, rule_text, category) "
                    "VALUES (%s, %s, %s, %s)",
                    [(trial_id, r["rule_id"], r["rule_text"], r["category"]) for r in rules],
                )


def get_trial(trial_id: str) -> dict | None:
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT trial_id, trial_name FROM trials WHERE trial_id = %s", (trial_id,)
            )
            row = cur.fetchone()
            if row is None:
                return None
            cur.execute(
                "SELECT rule_id, rule_text, category FROM rules WHERE trial_id = %s ORDER BY id",
                (trial_id,),
            )
            rules = cur.fetchall()
            return {
                "trial_id": row["trial_id"],
                "trial_name": row["trial_name"],
                "rules": [dict(r) for r in rules],
            }


def list_trials() -> list[dict]:
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT trial_id, trial_name FROM trials ORDER BY created_at")
            rows = cur.fetchall()
            result = []
            for row in rows:
                cur.execute(
                    "SELECT rule_id, rule_text, category FROM rules WHERE trial_id = %s ORDER BY id",
                    (row["trial_id"],),
                )
                result.append(
                    {
                        "trial_id": row["trial_id"],
                        "trial_name": row["trial_name"],
                        "rules": [dict(r) for r in cur.fetchall()],
                    }
                )
            return result


def count_assessments_for_trial(trial_id: str) -> int:
    """How many assessments currently reference this trial -- the number a
    delete would orphan. The audit trail is the whole point of this
    project, so a trial that has historical assessments against it can
    never be deleted silently."""
    with _connect() as conn:
        with conn.cursor() as cur:
            # Aliased because RealDictCursor keys by column name, so the
            # SQLite-era row[0] positional access no longer applies.
            cur.execute(
                "SELECT COUNT(*) AS n FROM assessments WHERE trial_id = %s", (trial_id,)
            )
            return cur.fetchone()["n"]


def delete_trial(trial_id: str) -> bool:
    """Delete a trial and its rules ONLY if no assessment references it.
    Returns False (and deletes nothing) when assessments exist -- the caller
    turns that into a 409, so deleting a trial can never silently orphan or
    destroy historical assessment evidence. When it does delete, the rules
    rows go via the schema's ON DELETE CASCADE."""
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT COUNT(*) AS n FROM assessments WHERE trial_id = %s", (trial_id,)
            )
            if cur.fetchone()["n"] > 0:
                return False
            cur.execute("DELETE FROM trials WHERE trial_id = %s", (trial_id,))
            return cur.rowcount > 0


def delete_assessment(assessment_id: str) -> bool:
    """Permanently remove an assessment. rule_results and the decision row
    are removed by the schema's ON DELETE CASCADE (see SCHEMA: both tables
    declare it on assessment_id) -- one transaction, nothing orphaned.
    Returns False if no such assessment exists (caller returns a 404)."""
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "DELETE FROM assessments WHERE assessment_id = %s", (assessment_id,)
            )
            return cur.rowcount > 0


def save_assessment(
    assessment_id: str,
    trial_id: str,
    patient_id: str,
    patient_record: str,
    suggested_status: str,
    provider_used: str,
    model_used: str,
    rule_results: list[dict],
):
    """Persist an assessment plus all of its per-rule results in one
    transaction -- the two must never be observable out of sync."""
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO assessments "
                "(assessment_id, trial_id, patient_id, patient_record, suggested_status, provider_used, model_used) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s)",
                (
                    assessment_id,
                    trial_id,
                    patient_id,
                    patient_record,
                    suggested_status,
                    provider_used,
                    model_used,
                ),
            )
            if rule_results:
                cur.executemany(
                    "INSERT INTO rule_results (assessment_id, rule_id, rule_text, status, evidence) "
                    "VALUES (%s, %s, %s, %s, %s)",
                    [
                        (
                            assessment_id,
                            rr["rule_id"],
                            rr["rule_text"],
                            rr["status"],
                            rr["evidence"],
                        )
                        for rr in rule_results
                    ],
                )


def get_assessment(assessment_id: str) -> dict | None:
    """Rehydrate an assessment by joining across all three tables:
    assessments + rule_results + decisions. A decision row only exists if
    one was recorded, so decision/decision_reason are None for undecided
    assessments -- same shape the API returned before SQLite existed."""
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT assessment_id, trial_id, patient_id, suggested_status, provider_used, model_used "
                "FROM assessments WHERE assessment_id = %s",
                (assessment_id,),
            )
            row = cur.fetchone()
            if row is None:
                return None
            cur.execute(
                "SELECT rule_id, rule_text, status, evidence FROM rule_results "
                "WHERE assessment_id = %s ORDER BY id",
                (assessment_id,),
            )
            rule_results = cur.fetchall()
            cur.execute(
                "SELECT decision, decision_reason FROM decisions WHERE assessment_id = %s",
                (assessment_id,),
            )
            decision = cur.fetchone()
            return {
                "assessment_id": row["assessment_id"],
                "trial_id": row["trial_id"],
                "patient_id": row["patient_id"],
                "suggested_status": row["suggested_status"],
                "provider_used": row["provider_used"],
                "model_used": row["model_used"],
                "rule_results": [dict(r) for r in rule_results],
                "decision": decision["decision"] if decision else None,
                "decision_reason": decision["decision_reason"] if decision else None,
            }


def list_assessments() -> list[dict]:
    """Lightweight summary of every assessment, newest first, for the
    History view. Deliberately NO rule_results -- the full nested detail
    stays on get_assessment()/GET /assessments/{id}. Left join keeps
    undecided assessments in the list with decision/decision_reason None."""
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT a.assessment_id, a.trial_id, a.patient_id, "
                "a.suggested_status, a.created_at, "
                "d.decision, d.decision_reason "
                "FROM assessments a "
                "LEFT JOIN decisions d ON d.assessment_id = a.assessment_id "
                "ORDER BY a.created_at DESC, a.assessment_id DESC"
            )
            return [dict(r) for r in cur.fetchall()]


def set_decision(assessment_id: str, decision: str, reason: str | None) -> bool:
    """Record the coordinator's decision. Returns False (and records
    nothing) if the assessment doesn't exist -- the caller turns that into
    a 404, so an unknown id can never silently invent a decision row."""
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT 1 FROM assessments WHERE assessment_id = %s", (assessment_id,)
            )
            if cur.fetchone() is None:
                return False
            cur.execute(
                "INSERT INTO decisions (assessment_id, decision, decision_reason) VALUES (%s, %s, %s) "
                "ON CONFLICT (assessment_id) DO UPDATE SET "
                "decision = EXCLUDED.decision, decision_reason = EXCLUDED.decision_reason",
                (assessment_id, decision, reason),
            )
            return True
